### ISSUE TITLE
 Liquid Exception: incomplete "\n" on UTF-16LE in _layouts/default.html

### ISSUE THREAD

**Issue by agussuhartono** [mmistakes/made-mistakes-jekyll#20]
I'm Install mademistake and get error :

Liquid Exception: incomplete  "\n" on UTF-16LE in _layouts/default.html

No line number information

**Comment by mmistakes** [comment]
Not sure I've never come across such an error with Jekyl before. This could be a bunch of different things. I haven't released this as a "theme" like my other Jekyll projects so there could unfinished bits in there somewhere, an incompatible plugin, your content, etc.
