### ISSUE TITLE
AMP pages

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/made-mistakes-jekyll#21]
Investigate [amp-jekyll](https://github.com/juusaw/amp-jekyll) plugin and possible use.

**Comment by daviddarnes** [comment]
Looked at https://mercury.postlight.com/? Might save you some work

**Comment by mmistakes** [comment]
Thanks @daviddarnes. I did try that out but it's parser didn't like something with my pages. I'm guessing it has something to do with Cloudflare and my `https` setup. It tends to block a bunch of services like this.

![screen shot 2016-08-17 at 10 29 35 am](https://cloud.githubusercontent.com/assets/1376749/17740135/85271eb0-6465-11e6-8d8d-344f764835e4.png)

**Comment by mmistakes** [comment]
Was able to get it working on pages where I don't have a lot of images. Pretty sure their parser chokes on my large photos in the `<picture>` elements.

**Comment by daviddarnes** [comment]
Ah ok I see, I was beginning to wonder as I'm on https with CloudFlare and it works fine. I've yet to implement `<picture>` for my images

**Comment by daviddarnes** [comment]
FYI I've had some poor results from adding AMP to my articles, they come up in google results but only for a few days. I've yet to see a serious benefit, other than a slight speed boost

**Comment by mmistakes** [comment]
Same here @daviddarnes. I've enabled it with Wordpress blogs for testing since it's fairly trivial to turn on. Really depends on the page content I've found. Unless you can do some sort of bespoke solution to make sure it's all marked up right you can lose a bunch in the conversion.

It especially starts to break down when someone hits an AMP page and then abandons because there is no navigation to browse around. Or if they follow an internal link on that page they end up on a non-AMP version. Pretty poor experience if you ask me.

**Comment by daviddarnes** [comment]
Hmm, makes me wonder if I should remove it if it's causing bad conversions 😲

**Comment by mmistakes** [comment]
It's worth testing that's for sure. It depends on your content and audience. Since it only really applies to mobile there's probably a big dropoff there anyways.

What kind of stinks about it is Google dangles this carrot that makes it seem like you'll get some SEO juice from it. Less so now, but more when they'd promote AMP "news" articles at the top with a stronger visual cue than the little lightning bolt they have now. But still...

Even if you do happen to get more traffic because of an AMPlified page I'd imagine the chance of visitors sticking around go away. With a bland design/style, absence of navigation and other content it makes it hard to entice them otherwise.

Looks like a lot of this stuff will be addressed in the future... https://www.ampproject.org/roadmap/ Seems like a lot of wasted effort to maintain a separate version of your content though. Smells like `m.domain.com` crap all over again.

**Comment by daviddarnes** [comment]
I feel the same way. I really thought it was some sort of short term fix for heavy loading sites. All those news sites that struggle to load could supply a faster, more lean, page for mobile users to load.

Oh well, at least it's sparked a healthy discussion! I feel like all the above is article worthy! 😄

**Comment by mmistakes** [comment]
Agreed! Still trying to find the time to write up converting Disqus comments into static-based ones... Hahah
