### ISSUE TITLE
Auto convert Markdown images into Srcset equivalent

### ISSUE THREAD

**Issue by mmistakes** [mmistakes/made-mistakes-jekyll#22]
Investigate better way of handling responsive images by writing in Markdown and replacing with Srcset markup. Possibly [via a plugin](https://gist.github.com/mmistakes/77c68fbb07731a456805a7b473f47841).

References:
- https://github.com/wildlyinaccurate/jekyll-responsive-image/issues/15
- https://github.com/jekyll/jekyll-assets/issues/157

**Comment by psirek** [comment]
Any thoughts on how you would implement this now? The easy way might be to extend your markdown_img_replacement.rb plugin to create the needed scrsets like in your page__cover.html file and put all files in the feature image folder. Trying to find a solution myself for my fork of this site.

**Comment by mmistakes** [comment]
@psirek The Markdown to `srcset` part is easy, its taking the image asset and generating the array of resized versions that's tricky.

Originally I was going to use the [Jekyll picture tag plugin](https://github.com/robwierzbowski/jekyll-picture-tag), but imagemagick was way to slow for me. I haven't found a good way to pipe it through [Sharp](https://github.com/lovell/sharp), which is much faster. I use a Gulp task to do it, but it's not ideal since the responsive image markup I'm generating is assuming the image assets will be there too...

**Comment by mmistakes** [comment]
@psirek How [Gatsby handles all of this](https://www.gatsbyjs.org/packages/gatsby-image/) is one of my main motivators for considering switching away from Jekyll.

**Comment by mmistakes** [comment]
If you don't have a lot of images the plugin gist above should do the trick when used with the Jekyll picture tag plugin. I believe the maintainers of that plugin recently rewrote it to support `srcset` markup which is nice.

So in theory that little image replacement plugin above can take vanilla Markdown image syntax, convert it to `{% picture %}` tags, which then would be handled by picture tage plugin and generate the responsive image markup along with all image assets. No checking links or any of that nonsense either.

I would have went that route but using Imagemagick to generate 20k images would have killed my build process. Instead I'm using a [variation on that image replacement plugin](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_plugins/markdown_img_replacement.rb) to take Markdown images pepper in some lazyload attributes to greatly improve page performance.

And if you're curious I have [test Gatsby repo](https://github.com/mmistakes/gatsby-test/issues/1) where I've been playing with it.

**Comment by psirek** [comment]
I will look into it, Jekyll Picture Tag should be enough for me since I do not expect to go over 500 images anytime soon. And I will take a look at Gatsby early next year when the holidays has passed.

Thanks for pointing me in the right direction, much appreciated!
