### ISSUE TITLE
bundle install fail on Mac OSX El Capitan

### ISSUE THREAD

**Issue by suredream** [mmistakes/made-mistakes-jekyll#477]
Very beautiful jekyll-based blog, however,  I have no luck to run it on my Mac.

When $ bundle install

pkg-config could not be used to find libiconv
Please install either `pkg-config` or the pkg-config gem per

    gem install pkg-config -v "~> 1.1.7"

checking for iconv using pkg-config libiconv... no
-----
libiconv is missing.  Please locate mkmf.log to investigate how it is failing.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

**Comment by mmistakes** [comment]
That's related to node-gyp and [Sharp](http://sharp.dimens.io/en/stable/install/) which is used to generate responsive images in one of the Gulp tasks. 

I had a hell of a time getting both to install with errors. They're are instructions on its repo that might be helpful for you. 

Also you'll likely need to install Node.js and dependencies with `npm install` as I use Gulp to spin up Jekyll.

https://github.com/nodejs/node-gyp#installation

**Comment by suredream** [comment]
I've tried but no luck.

Thank you though.

BYW, very nice personal blog. Make it sooo hard to even find an equivalent.

**Comment by mmistakes** [comment]
You could try simplifying things and removing all of the Gulp stuff related to responsive images. I've built things in a very specific way for my needs, that likely can be ripped out if you know what you're doing.
