### ISSUE TITLE
Text Callouts for Basically Basic Theme?

### ISSUE THREAD

**Issue by twhite96** [mmistakes/made-mistakes-jekyll#624]
Looking through this repo trying to figure out if I can glean how you did the text callouts `danger`, `warning` etc so I can add them to Basically Basic. Is there already a way to do this in that theme that I am missing and if not could you advise how to accomplish this or add it to that theme?

**Comment by mmistakes** [comment]
You'll need to install a [simple notice plugin](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_plugins/notice.rb) into `_plugins/` and then you'll be able to wrap Markdown with a [`{% notice %}` tag](https://github.com/mmistakes/made-mistakes-jekyll#notices).

**Comment by mmistakes** [comment]
You'll also need to [CSS](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/assets/stylesheets/_notices.scss) to style the various notices or match the classes to what's in BB. I forget if I added notice classes in that theme.

**Comment by twhite96** [comment]
Thanks Michael
