### ISSUE TITLE
Improve Site build times with cached includes

### ISSUE THREAD

**Issue by ashmaroli** [mmistakes/made-mistakes-jekyll#629]
:wave: Michael

Did you know that you can cache rendered outputs from *stateless* includes and improve your build times with a plugin..?
The plugin is called [jekyll-include-cache](https://github.com/benbalter/jekyll-include-cache) and is whitelisted for use at GHP
(just not bundled by default, *since its dangerous for novices*)

The plugin can be used to cache any "include" that does not change its output from page-to-page.
Such includes can simply be plain HTML without any Liquid or an include that **only references the global constant {{ site }}** e.g., [src/_includes/footer.html](https://github.com/mmistakes/made-mistakes-jekyll/blob/master/src/_includes/footer.html)

I did not submit a PR because I thought I'd gather your feedback first and allow you to implement it first-hand so that you know where it can be used and **where it should not be used**..

Results from `--profile` on my system show that you *may be able to shave of ~15 seconds* but I may be wrong..

**Comment by mmistakes** [comment]
Nice! I definitely have a few includes that could benefit from this. Will have to give it a try.

Not sure of the impact it'll have. Most of my build times are stuck building tons of paginated tag/category pages with the jekyll-paginate-v2 plugin.

**Comment by ashmaroli** [comment]
> Not sure of the impact it'll have

I'm guessing at most 15-20s.. Also, you can gain more time by avoiding unnecessary fragmentation.
For example, inserting the contents of `related.html` include into `post` layout will free Jekyll from having to *parse and render the include* each time the `post` layout is rendered (exactly 1002 times according to output from `--profile`)
Of course, the above observation would be futile if `related.html` was being included in more than one layout.
