### ISSUE TITLE
bigfoot.js popup overflowing

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/made-mistakes-jekyll#631]
Hi @mmistakes 
I just notices a bug with bigfoot while implimenting on my [website](http://localhost:4000/blog/articles/mesmerising-chaupais-from-ramayan/), and is present on [your website](https://mademistakes.com/about/) too.

**Bug -** On mobile device (my mobile screen res - 720x1280), the popup overflow from the screen if shown on extreme left on the screen.

I thought of putting this issue on bigfoot.js repo, nut the project is stale with many issues pending. However I found this opened issue which might be the same -https://github.com/lemonmade/bigfoot/issues/46

I tried using `positionContent: "true"` as mentioned on http://bigfootjs.com but no success.

_**Hoping that you can catch something...**_

### **Explanation -** 

**On your website (about page)-** - 
I **slowly** resized screen in chrome (desktop) to emulate the bug.

![image](https://user-images.githubusercontent.com/17742733/46288563-bb72bc80-c5a3-11e8-8e15-1e1fea8f5026.png)
   
  
**On my website -** 
 [this page](https://kulbhushan-chand.github.io/blog/articles/mesmerising-chaupais-from-ramayan/) - happens on mobile device only

![screenshot_20181001-073003](https://user-images.githubusercontent.com/17742733/46288680-28865200-c5a4-11e8-9700-1d1ffa3be788.png)

**Comment by mmistakes** [comment]
I'm not going to be of much help since JavaScript isn't my forte. If it's an issue for you and BigFoot.js appears to be abandoned, then you might have to use something else.

Closing as this is an upstream issue.

**Comment by mmistakes** [comment]
Also, might be a browser thing. I'm not seeing the positioning problem you are, even when I resize the browser window. Seems to correctly move the overlay so it's not overflowing outside the viewport.

**Comment by Kulbhushan-Chand** [comment]
Visit my website link on your mobile - https://kulbhushan-chand.github.io/blog/articles/mesmerising-chaupais-from-ramayan/

**Comment by mmistakes** [comment]
Looks fine to me on my iPhone and in Chrome dev tools. None of the BigFoot overlays are cutting off for me.

**Comment by Kulbhushan-Chand** [comment]
Weird... I can replicate problem in google device toolbar - responsive screen with width 400px

Can you check in the same way

![image](https://user-images.githubusercontent.com/17742733/46293547-79e90e00-c5b1-11e8-8933-fb2d3b1d4dff.png)

**Comment by mmistakes** [comment]
Looks fine.

![image](https://user-images.githubusercontent.com/1376749/46293868-96118e80-c562-11e8-99c5-1f9c07286503.png)

**Comment by mmistakes** [comment]
Looks fine for me on iOS, Chrome (Windows), Chrome (macOS).

This seems like an issue with your browser. You probably have a plugin/extension installed that is messing with the page. Have you tried other browsers like Firefox and Safari? That will clue you in as to what's going on since this appears to be only your machine.

**Comment by Kulbhushan-Chand** [comment]
**Bug present on -**
- android phone chrome browser (always),
- windows chrome (manual resizing windows, so that footnote link is very close to right end of screen / or by using device toolbar-responsive-425px width)
- iOS chrome (manual resizing windows, so that footnote link is very close to right end of screen / or by using device toolbar-responsive-425px width)
- windows Firefox browser (manual resizing windows, so that footnote link is very close to right end of screen)

**Bug absent on -**
- android phone samsung native internet browser
- windows Firefox browser (using device toolbar-responsive-425px width)

**Comment by mmistakes** [comment]
Sorry don't have any other suggestions. Best you can do is file a bug report on BigFoot.js

I don't have any control over their plugin, nor do I know JavaScript well enough to propose a fix.

**Comment by Kulbhushan-Chand** [comment]
Bug filed on bigfoot repo here - https://github.com/lemonmade/bigfoot/issues/66
I appreciate your kind help and direction. You're awesome 👍

**Comment by Kulbhushan-Chand** [comment]
I narrowed down to the part may be responsible for this bug.
I checked the javascript code and tried to understand if I can call this [function  ](https://github.com/lemonmade/bigfoot/blob/981404aa9fd8d5ca979f9310333b9670990ffa1c/dist/bigfoot.js#L393)at the time of popover creation, but my limited knowledge of javascript plays a hindrance. 🤔 

![2018-10-02_18-26-17](https://user-images.githubusercontent.com/17742733/46350030-4d94c680-c671-11e8-8ed6-8732a0de7d2f.gif)
