### ISSUE TITLE
mixin not found

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/made-mistakes-jekyll#634]
Hi,
I am not able to find this function [breakpoint](https://github.com/mmistakes/made-mistakes-jekyll/blob/3850ada12a8d249af64e6ac2ec10358a96a4acdc/src/assets/stylesheets/_footer.scss#L18) in any of the mixin file.
The jekyll is throwing error - 
` Undefined mixin 'breakpoint`
Am I doing something wrong?

**Comment by mmistakes** [comment]
Not sure what you're doing wrong but the breakpoint mixin is in [`/styelsheets/vendor/breakpoint`](https://github.com/mmistakes/made-mistakes-jekyll/tree/master/src/assets/stylesheets/vendor/breakpoint).

**Comment by Kulbhushan-Chand** [comment]
Oh.. My apologies.. Just noticed the folder. 
Looks like the situation `when I desperately searches for spectacles, only to realize in the end -- I was already wearing it `
Thanks
