### ISSUE TITLE
Why you are using wufoo.js?

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/made-mistakes-jekyll#638]
Hi @mmistakes ,

**_Kindly help with a question related to your website_**

Just like your contact form , I have managed to make wufoo working, without using `<script>{% include_cached wufoo.js %}</script>`

**Doubt 1** -  I was wondering what is the use of including above script? Nowhere on the original site of wufoo they have mentioned about this JS code

**Doubt 2** - Are you using hidden text box to prevent spambots from spamming the form?
i.e. this one -  `<textarea name="comment" id="comment" rows="1" cols="1"></textarea>`

**Comment by mmistakes** [comment]
No idea. When I setup the wufoo form years ago they had a script as part of the form code. I haven't checked their site in years, for all I know they removed it.

It's probably just used for form validation and maybe includes a honeypot for spam bots. Your guess is as good as mine...
