### ISSUE TITLE
html in robots.txt file

### ISSUE THREAD

**Issue by Kulbhushan-Chand** [mmistakes/made-mistakes-jekyll#647]
Hi @mmistakes 

**I have a basic doubt -** 

In this line https://github.com/mmistakes/made-mistakes-jekyll/blob/7373c38140bfd14a0caad88767d20e7062a6d146/src/robots.txt#L1

The robots.txt file contains two ` --- lines`, so the jekyll fill this file with html, and hence the chrome developer audit page shows it as following error -

![image](https://user-images.githubusercontent.com/17742733/48410535-da4c9d00-e764-11e8-943b-48542f1e21d5.png)

**On my website -** 

![image](https://user-images.githubusercontent.com/17742733/48410744-8db59180-e765-11e8-94b1-e9ee5a38a3b2.png)

**However on your website -** 

![image](https://user-images.githubusercontent.com/17742733/48410716-75de0d80-e765-11e8-9b60-f950dbc79be7.png)

**What I am doing wrong?**

**Comment by mmistakes** [comment]
Without seeing your source I can only guess.
But my guess would be you're hosting with GitHub Pages, and they are [automatically assigning `layout: default`](https://github.com/benbalter/jekyll-default-layout) to all of your static documents.

That's why your `robots.txt` content is wrapped with `<doctype html>` and the copyright text.
Use this for your front matter:

```
---
layout: null
---
```

**Comment by Kulbhushan-Chand** [comment]
Yes I am hosting with GitHub Pages.

**Thanks** for the link, where it was mentioned to use `layout: null`, which exempt the page from default layout. Honestly I would never be able to boil down my search to that page.

```
---
layout: null
---
User-agent: *
Disallow:
Sitemap: {{ site.url }}/sitemap.xml
```

**Comment by mmistakes** [comment]
GitHub Pages support would have hopefully be able to help you pin down the issue.

**Comment by Kulbhushan-Chand** [comment]
Ohh, I forgot to add that the problem solved by adding `layout: null`.
