### ISSUE TITLE
Homepage not showing posts

### ISSUE THREAD

**Issue by claudiuconstantin** [mmistakes/made-mistakes-jekyll#652]
I am trying to create a new jekyll site with this theme installed as a gem. I went through all the steps in the [Getting started](https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/) guide ("Starting from jekyll new"), but the default Recent articles homepage doesn't seem to pick up the posts in the _posts folder. What can cause this issue, is there any additional configuration necessary?

![image](https://user-images.githubusercontent.com/1537573/48660384-68789a00-ea69-11e8-946a-5d7dca64cce0.png)

**Comment by mmistakes** [comment]
Hard to say. Please provide a sample repo. Can't troubleshoot without it.

**Comment by claudiuconstantin** [comment]
[This](https://github.com/claudiuconstantin/minimal-mistakes-test) should be it

**Comment by mmistakes** [comment]
This repo isn't for my Minimal Mistakes theme. Please open an issue on that repo.

https://github.com/mmistakes/minimal-mistakes

**Comment by claudiuconstantin** [comment]
Ah, my bad, sorry for that. I just created [this issue](https://github.com/mmistakes/minimal-mistakes/issues/1950) over the correct repo.
