### ISSUE TITLE
No build. "fs.js:125     throw err;     ^"

### ISSUE THREAD

**Issue by pateskinasy** [mmistakes/made-mistakes-jekyll#685]
Hi Michael, I can't manage to build. I get the following after calling `gulp`: 

```
 fs.js:125
    throw err;
```

I've then called `npm install` and get `fatal error: too many errors emitted, stopping now [-ferror-limit=]`
 . Any pointers?

**Comment by mmistakes** [comment]
Your best bet is searching Google and Stackoverflow. It could be any of the various Node packages that didn’t install properly for you.

**Comment by pateskinasy** [comment]
Thanks @mmistakes. `Yarn install `on step 2 fails because of dependencies that only work with Node.js up to version 9. My suggestion for others having issues: Install Node.js 9 with nvm.
