### ISSUE TITLE
git submodule update --recursive --remote --merge --force ? How do you keep your submodule updated with the latest?

### ISSUE THREAD

**Issue by pateskinasy** [mmistakes/made-mistakes-jekyll#689]
Hi Michael,

Quick question on your setup with a separate image repo (approach I have also been following). Do you run a `git submodule update --recursive --remote --merge --force` to update your submodule every time you add a new image (to your separate image repo) or have you managed to automate this update through your code (through some git config or maybe sth else)?

Thanks in advance!

**Comment by mmistakes** [comment]
I use a GUI frontend to Git with [Sourcetree](https://www.sourcetreeapp.com/).
Not sure what command it runs, but whenever I add a new image to images submodule, I'll see a file in the interface that needs to be committed.

**Comment by pateskinasy** [comment]
Thanks for the response.

So, to clarify:

- When you upload an image to your local repo for _https://github.com/mmistakes/made-mistakes-images_ you get the file on your Sourcetree GUI ready to commit
- When you do commit you now have the image in _https://github.com/mmistakes/made-mistakes-images_
- How do you get https://github.com/mmistakes/made-mistakes-jekyll images folder (the submodule) to get updated when you trigger a new deploy in Netlify?
- The submodule is tied to a specific commit in your image repo (In your case currently that is "661e083" from "images @ 661e083", but that is now commit is actually now outdated since your image repo has now been updated with a new image
- At least in my case I can only make the images folder in my source code repo update if I run` git submodule update --recursive --remote --merge --force` locally to update my source code image folder and then all flows well from there.\

I'm guessing you may have some automation in place to get it to work seamlessly?

**Comment by mmistakes** [comment]
No automation on my part. When I commit to the images repo, in my main repo that has the submodule, the GUI in Sourcetree will show there's a commit tied to the images repo that also needs committing.

Since I never just add an image without tying it to a post or page it's not that big of a deal. I know to comit to the images repo, and then commit that change to the master repo.

**Comment by pateskinasy** [comment]
Thanks @mmistakes. My issue seems to stem from Github Desktop (there seems to be a substantial amount of improvements to be done on the submodules front there). 

Thanks for helping me understand your workflow. Cheers!
