### ISSUE TITLE
Can I cannibalize your "Terms and Privacy Policy" page text?

### ISSUE THREAD

**Issue by TheNewbieWoodworker** [mmistakes/made-mistakes-jekyll#703]
Not an "issue" per se, but I don't know how else to ask you this. As the title says, do you mind if I cannibalize your "Terms and Privacy Policy" from your page: https://mmistakes.github.io/minimal-mistakes/terms/#disclosure-policy

Thanks.

**Comment by mmistakes** [comment]
Feel free. Most of it is boilerplate directly from all the sources cited anyways. Nothing proprietary in there.

**Comment by TheNewbieWoodworker** [comment]
I figured as much, but I had to ask! Thanks!!
