### ISSUE TITLE
Pagination: Is enabled, but I couldn't find any pagination page

### ISSUE THREAD

**Issue by ngocsangyem** [mmistakes/made-mistakes-jekyll#707]
After I run `npm install` and `bundle install` then `bundle exec jekyll serve`. I have not change any config file yet but I got this message:
> Pagination: Is enabled, but I couldn't find any pagination page. Skipping pagination. Pages m
ust have 'pagination: enabled: true' in their front-matter for pagination to work.

**Comment by mmistakes** [comment]
I think this is just a warning from jekyll-paginate-v2. You likely don't have pagination enabled on any pages like I do. You can just disable all the pagination stuff in `_config.yml` if you're not using it.
