### ISSUE TITLE
autogenerate last_modified_at ?

### ISSUE THREAD

**Issue by copdips** [mmistakes/made-mistakes-jekyll#725]
Hello,

I see in almost each your post's header, you have a line of `last_modified_at:`, is it set manually ?
Could we autogenerate it upon the file modification timestamp or git push timestamp, etc. ?

It seems that `page.date` is autogenerated.

**Comment by mmistakes** [comment]
`page.date` comes from Jekyll and it's filename convention for posts e.g. `YYYY-MM-DD-my-awesome-post.md`

I'm manually adding a timestamp to `last_modified_at` when I remember. I haven't looked in some time so there might be a better way to automate it now with some tooling, but I use the [Insert Date String](https://marketplace.visualstudio.com/items?itemName=jsynowiec.vscode-insertdatestring) extension in Visual Studio Code. It's just a keyboard shortcut away to insert into my posts/pages after I update.

**Comment by copdips** [comment]
Thx for your confirmation. I will set it by the plugin too.
But it's nice to have soemthing to automate it.
